---
apiVersion: v1
kind: ConfigMap
metadata:
  name: imageswap-mwc-template
  namespace: {{ .Release.Namespace }}
data:
  imageswap-mwc: |
    apiVersion: admissionregistration.k8s.io/v1
    kind: MutatingWebhookConfiguration
    metadata:
      name: imageswap-webhook
      labels:
        app: imageswap
        resource: mutatingwebhookconfiguration
    webhooks:
      - name: imageswap.webhook.k8s.twr.io
        clientConfig:
          service:
            name: imageswap
            namespace: {{ .Release.Namespace }}
            path: "/"
            port: 8181
          caBundle: $CA_BUNDLE
        rules:
          - operations:
              - CREATE
              - UPDATE
            apiGroups:
              - "*"
            apiVersions:
              - "*"
            resources:
              - "pods"
        sideEffects: None
        admissionReviewVersions: ["v1"]
        failurePolicy: Fail
        reinvocationPolicy: IfNeeded
        namespaceSelector:
          matchLabels:
            k8s.twr.io/imageswap: "enabled"

---
## This ConfigMap contains the meat and potatoes - the image-rewrite logic.
apiVersion: v1
data:
  maps: |
    {{- .Files.Get "maps.yaml" | nindent 4}}

kind: ConfigMap
metadata:
  creationTimestamp: null
  name: imageswap-maps
  namespace: {{ .Release.Namespace }}
