---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  labels:
    app: imageswap
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
  name: imageswap
  namespace: "{{ .Release.Namespace }}"
spec:
  replicas: {{ default 2 .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: imageswap
      release: "{{ .Release.Name }}"
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: "RollingUpdate"
  template:
    metadata:
      labels:
        app: imageswap
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        heritage: "{{ .Release.Service }}"
        release: "{{ .Release.Name }}"
    spec:
      affinity:
        {{- toYaml .Values.affinity | nindent 8 }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      serviceAccountName: imageswap-sa
      securityContext:
        runAsUser: 1898
        runAsGroup: 1898
      initContainers:
        - name: imageswap-init
          image: {{ .Values.deployment.init.image | quote }}
          command: [/app/imageswap-init.py]
          imagePullPolicy: Always
          securityContext:
            allowPrivilegeEscalation: false
          env:
            - name: IMAGESWAP_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: IMAGESWAP_NAMESPACE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: FLASK_ENV
              value: "production"
            - name: PYTHONUNBUFFERED
              value: "TRUE"
            - name: IMAGESWAP_MODE
              value: "MAPS"
            - name: IMAGESWAP_LOG_LEVEL
              value: "INFO"
            {{- with .Values.extraEnv }}
              {{- toYaml . | nindent 10 }}
            {{- end }}
          volumeMounts:
            - name: imageswap-tls
              mountPath: /tls
            - name: imageswap-mwc
              mountPath: /mwc
      containers:
        - name: imageswap
          image: {{ .Values.deployment.imageswap.image | quote }}
          resources: {{- toYaml .Values.resources | nindent 12 }}
          command: ["gunicorn", "imageswap:app", "--config=config.py"]
          imagePullPolicy: Always
          securityContext:
              allowPrivilegeEscalation: false
          env:
            - name: IMAGESWAP_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: IMAGESWAP_NAMESPACE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: FLASK_ENV
              value: "production"
            - name: PYTHONUNBUFFERED
              value: "TRUE"
            - name: IMAGESWAP_MODE
              value: "MAPS"
            - name: IMAGESWAP_LOG_LEVEL
              value: "INFO"
            {{- with .Values.extraEnv }}
              {{- toYaml . | nindent 10 }}
            {{- end }}
          volumeMounts:
            - name: imageswap-tls
              mountPath: /tls
            - name: imageswap-maps
              mountPath: /app/maps
      volumes:
        - name: imageswap-mwc
          configMap:
              name: imageswap-mwc-template
              items:
              - key: imageswap-mwc
                path: imageswap-mwc.yaml
        - name: imageswap-maps
          configMap:
              name: imageswap-maps
              items:
              - key: maps
                path: imageswap-maps.conf
        - name: imageswap-tls
          emptyDir: {}
