{{ if .Values.hpa.enabled}}
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: imageswap
  namespace: {{ .Release.Namespace }}
  labels:
    app: imageswap
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"

spec:
  maxReplicas: 6
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: imageswap
  targetCPUUtilizationPercentage: 80
{{- end -}}