apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: imageswap-pdb
  namespace: "{{ .Release.Namespace }}"
  labels:
    app: imageswap
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: imageswap
      chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
      heritage: "{{ .Release.Service }}"
      release: "{{ .Release.Name }}"

