---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: imageswap-write-crb
  labels:
    app: imageswap
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
roleRef:
  kind: ClusterRole
  name: imageswap-write
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: imageswap-sa
    namespace: "{{ .Release.Namespace }}"

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: imageswap-read-crb
  labels:
    app: imageswap
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
roleRef:
  kind: ClusterRole
  name: imageswap-read
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: imageswap-sa
    namespace: "{{ .Release.Namespace }}"

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: imageswap-ops-rb
  namespace: "{{ .Release.Namespace }}"
  labels:
    app: imageswap
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
roleRef:
  kind: Role
  name: imageswap-ops
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: imageswap-sa
