---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: imageswap-sa
  namespace: "{{ .Release.Namespace }}"
  labels:
    app: imageswap
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
