---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "imageswap.fullname" . }}-write
  namespace: "{{ .Release.Namespace }}"
  labels:
    app: {{ template "imageswap.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
rules:
  - apiGroups:
      - admissionregistration.k8s.io
      - certificates.k8s.io
      - ""
    resources:
      - mutatingwebhookconfigurations
      - certificatesigningrequests
      - certificatesigningrequests/approval
      - certificatesigningrequests/status
      - signers
    verbs:
      - get
      - list
      - watch
      - create
      - patch
      - update
      - delete
      - approve
      - sign

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "imageswap.fullname" . }}-read
  labels:
    app: {{ template "imageswap.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - get
      - list
      - watch

---
# Define role for OPA/kube-mgmt to update configmaps with policy status.
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "imageswap.fullname" . }}-ops
  namespace: "{{ .Release.Namespace }}"
  labels:
    app: {{ template "imageswap.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
      - create
      - patch
      - update
      - delete
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
      - patch
      - update
