---
apiVersion: v1
kind: Service
metadata:
  name: {{template "imageswap.fullname" .}}
  namespace: "{{ .Release.Namespace }}"
  labels:
    app: {{template "imageswap.fullname" .}}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
spec:
  ports:
    - name: https
      port: 8181
      targetPort: 5000
  selector:
    app: {{template "imageswap.fullname" .}}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
