---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "imageswap.fullname" . }}-sa
  namespace: "{{ .Release.Namespace }}"
  labels:
    app: {{ template "imageswap.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
